version: '3'

services:
  # Сервис с базой данных PostgreSQL
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${PRODUCT_USER}
      POSTGRES_PASSWORD: ${PRODUCT_PASSWORD}
      POSTGRES_DB: ${NAME_DB}
    ports:
      - "${PRODUCT_PORT}:5432"

  # Сервис с Django и Poetry
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SECRET_KEY: ${TOKEN_DJANGO_APP}
      DJANGO_DEBUG: ${DEV}
      DJANGO_ALLOWED_HOSTS: ${APP_HOST}
      DATABASE_URL: postgres://${PRODUCT_USER}:${PRODUCT_PASSWORD}@db:5432/${NAME_DB}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: